// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBI6S8dYj02Y__0efeMvwyomS7ciNogfY0',
    appId: '1:30267142845:web:7fdf559b7de3f92f973dd4',
    messagingSenderId: '30267142845',
    projectId: 'ultimate-e-commerce-app',
    authDomain: 'ultimate-e-commerce-app.firebaseapp.com',
    storageBucket: 'ultimate-e-commerce-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQYCWU3ys0734WWpS84cffJsAxzhmfmzA',
    appId: '1:30267142845:android:cdd94c5010a0f049973dd4',
    messagingSenderId: '30267142845',
    projectId: 'ultimate-e-commerce-app',
    storageBucket: 'ultimate-e-commerce-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6oSnFg03GEYcMyMHTy0xuiXrtFM2m-4k',
    appId: '1:30267142845:ios:941a2edc0cdd69d3973dd4',
    messagingSenderId: '30267142845',
    projectId: 'ultimate-e-commerce-app',
    storageBucket: 'ultimate-e-commerce-app.appspot.com',
    iosBundleId: 'com.example.paymentMethod',
  );
}
